[package]
description = "Rust tools for the nand2tetris course"
name = "nand2tetris"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ashdnazg/nand2tetris"
readme = "README.md"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = { version = "0.35", optional = true }
eframe = { version = "0.17.0", optional = true }
nom = "7.1.1"
hashbrown = "0.12"

[profile.release]
debug = true

[features]
default = ["legacy_emulators", "emulators"]
legacy_emulators = ["dep:sdl2"]
emulators = ["dep:eframe"]


[[bin]]
name = "legacy_hardware_emulator"
required-features = ["legacy_emulators"]

[[bin]]
name = "legacy_vm_emulator"
required-features = ["legacy_emulators"]

[[bin]]
name = "vm_emulator"
required-features = ["emulators"]
